### ISSUE TITLE
cuDNN doesn't seem to work on Windows 8.1

### ISSUE THREAD

**Issue by jfolt** [deeplearning4j/deeplearning4j#1813]
I am able to train on GPU. But I don't seem to be able to run cuDNN on Windows 8.1.

I downloaded 0.4 examples, imported into Eclipse (with java 1.7 x64), and made only those 2 changes:

In the parent pom.xml:
`<nd4j.backend>nd4j-cuda-7.5</nd4j.backend>`

in the dl4j-examples pom.xml added this in the dependencies section:
`		<dependency>`
`		    <groupId>org.deeplearning4j</groupId>`
`		    <artifactId>deeplearning4j-cuda-7.5</artifactId>`
`		    <version>${dl4j.version}</version>`
`		</dependency>                 `

This is what I see when running Lenet example:

o.d.e.c.LenetMnistExample - Load data....

o.d.e.c.LenetMnistExample - Build model....
o.d.n.l.c.ConvolutionLayer - Could not load CudnnConvolutionHelper
java.lang.UnsatisfiedLinkError: no jnicuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[na:1.7.0_79]
	at java.lang.Runtime.loadLibrary0(Unknown Source) ~[na:1.7.0_79]
	at java.lang.System.loadLibrary(Unknown Source) ~[na:1.7.0_79]
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726) ~[javacpp-1.2.2.jar:1.2.2]
	at org.bytedeco.javacpp.Loader.load(Loader.java:501) ~[javacpp-1.2.2.jar:1.2.2]
Caused by: java.lang.UnsatisfiedLinkError: no cuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[na:1.7.0_79]
	at java.lang.Runtime.loadLibrary0(Unknown Source) ~[na:1.7.0_79]
	at java.lang.System.loadLibrary(Unknown Source) ~[na:1.7.0_79]
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726) ~[javacpp-1.2.2.jar:1.2.2]
	at org.bytedeco.javacpp.Loader.load(Loader.java:492) ~[javacpp-1.2.2.jar:1.2.2]
o.d.n.l.c.s.SubsamplingLayer - Could not load CudnnSubsamplingHelper
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.cudnn
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper$CudnnContext.createHandles(CudnnSubsamplingHelper.java:89) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper$CudnnContext.<init>(CudnnSubsamplingHelper.java:76) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper.<init>(CudnnSubsamplingHelper.java:105) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_79]
o.d.n.l.c.ConvolutionLayer - Could not load CudnnConvolutionHelper
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.cudnn
	at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper$CudnnContext.createHandles(CudnnConvolutionHelper.java:94) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper$CudnnContext.<init>(CudnnConvolutionHelper.java:78) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper.<init>(CudnnConvolutionHelper.java:136) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_79]
o.d.n.l.c.s.SubsamplingLayer - Could not load CudnnSubsamplingHelper
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.cudnn
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper$CudnnContext.createHandles(CudnnSubsamplingHelper.java:89) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper$CudnnContext.<init>(CudnnSubsamplingHelper.java:76) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper.<init>(CudnnSubsamplingHelper.java:105) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_79]
o.d.e.c.LenetMnistExample - Train model....
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 2.5576238169173227
o.d.o.l.ScoreIterationListener - Score at iteration 1 is 2.414856652833581

**Comment by saudet** [comment]
Could you call `Loader.load(cudnn.class)` as the first thing in the `main()` method and let me know what that throws? Thanks! BTW, I only tested with cuDNN 5, it might not work with 5.1 RC...

**Comment by AlexDBlack** [comment]
Just to add another data point: CuDNN is working fine on my machine (Win10). cudnn64_5.dll is on my path. @jfolt can you double check your path using "where cudnn64_5.dll"?

**Comment by jfolt** [comment]
I upgraded cudnn from v4 to v5. Installed v5 for Cuda 7.5 (not RC), but still see the same errors.

Note: cudnn (v4) did work for me with Theano.

@AlexDBlack, 
c:\>where cudnn64_5.dll
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin\cudnn64_5.dll

I am attaching the stack trace anyway (just in case you find any difference):

o.d.e.c.LenetMnistExample - Load data....


o.d.e.c.LenetMnistExample - Build model....
o.d.n.l.c.ConvolutionLayer - Could not load CudnnConvolutionHelper
java.lang.UnsatisfiedLinkError: no jnicuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[na:1.7.0_79]
	at java.lang.Runtime.loadLibrary0(Unknown Source) ~[na:1.7.0_79]
	at java.lang.System.loadLibrary(Unknown Source) ~[na:1.7.0_79]
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726) ~[javacpp-1.2.2.jar:1.2.2]
	at org.bytedeco.javacpp.Loader.load(Loader.java:501) ~[javacpp-1.2.2.jar:1.2.2]
Caused by: java.lang.UnsatisfiedLinkError: no cuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[na:1.7.0_79]
	at java.lang.Runtime.loadLibrary0(Unknown Source) ~[na:1.7.0_79]
	at java.lang.System.loadLibrary(Unknown Source) ~[na:1.7.0_79]
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726) ~[javacpp-1.2.2.jar:1.2.2]
	at org.bytedeco.javacpp.Loader.load(Loader.java:492) ~[javacpp-1.2.2.jar:1.2.2]
o.d.n.l.c.s.SubsamplingLayer - Could not load CudnnSubsamplingHelper
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.cudnn
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper$CudnnContext.createHandles(CudnnSubsamplingHelper.java:89) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper$CudnnContext.<init>(CudnnSubsamplingHelper.java:76) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper.<init>(CudnnSubsamplingHelper.java:105) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_79]
o.d.n.l.c.ConvolutionLayer - Could not load CudnnConvolutionHelper
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.cudnn
	at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper$CudnnContext.createHandles(CudnnConvolutionHelper.java:94) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper$CudnnContext.<init>(CudnnConvolutionHelper.java:78) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.CudnnConvolutionHelper.<init>(CudnnConvolutionHelper.java:136) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_79]
o.d.n.l.c.s.SubsamplingLayer - Could not load CudnnSubsamplingHelper
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.cudnn
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper$CudnnContext.createHandles(CudnnSubsamplingHelper.java:89) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper$CudnnContext.<init>(CudnnSubsamplingHelper.java:76) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at org.deeplearning4j.nn.layers.convolution.subsampling.CudnnSubsamplingHelper.<init>(CudnnSubsamplingHelper.java:105) ~[deeplearning4j-cuda-7.5-0.4.0.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_79]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_79]
o.d.e.c.LenetMnistExample - Train model....
o.d.o.l.ScoreIterationListener - Score at iteration 0 is 2.5576238169173227
o.d.o.l.ScoreIterationListener - Score at iteration 1 is 2.414856652833581
o.d.o.l.ScoreIterationListener - Score at iteration 2 is 2.7043355067739876
o.d.o.l.ScoreIterationListener - Score at iteration 3 is 2.2946867901265167
o.d.o.l.ScoreIterationListener - Score at iteration 4 is 1.8114470449680762

**Comment by jfolt** [comment]
@saudet - after I added this line, the example does not run at all, this is the stack trace:

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnicuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726)
	at org.bytedeco.javacpp.Loader.load(Loader.java:501)
	at org.bytedeco.javacpp.Loader.load(Loader.java:418)
	at org.bytedeco.javacpp.cuda.<clinit>(cuda.java:10)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.bytedeco.javacpp.Loader.load(Loader.java:473)
	at org.bytedeco.javacpp.Loader.load(Loader.java:434)
	at org.deeplearning4j.examples.convolution.LenetMnistExample.main(LenetMnistExample.java:36)
Caused by: java.lang.UnsatisfiedLinkError: no cuda in java.library.path
	at java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.lang.System.loadLibrary(Unknown Source)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726)
	at org.bytedeco.javacpp.Loader.load(Loader.java:492)
	... 7 more

**Comment by saudet** [comment]
I really can't reproduce that here. The only way that I can see this happening is if for some reason files are missing in the uber JAR. For example, can you make sure these files show up your archive?
```
$ unzip -v dl4j-examples-0.4-rc0-SNAPSHOT-bin.jar | grep dll
  645632  Defl:N   109447  83% 2016-07-13 16:42 96befaa5  org/bytedeco/javacpp/windows-x86_64/jnicublas.dll
  493568  Defl:N   108570  78% 2016-07-13 16:42 b628d0b6  org/bytedeco/javacpp/windows-x86_64/jnicuda.dll
  199168  Defl:N    41533  79% 2016-07-13 16:42 ed979294  org/bytedeco/javacpp/windows-x86_64/jnicudnn.dll
   55808  Defl:N    15308  73% 2016-07-13 16:42 22fda411  org/bytedeco/javacpp/windows-x86_64/jnicufft.dll
  160256  Defl:N    33510  79% 2016-07-13 16:42 f0cc85c1  org/bytedeco/javacpp/windows-x86_64/jnicufftw.dll
   49152  Defl:N    13485  73% 2016-07-13 16:42 2946e470  org/bytedeco/javacpp/windows-x86_64/jnicurand.dll
  422912  Defl:N    71947  83% 2016-07-13 16:42 1f466050  org/bytedeco/javacpp/windows-x86_64/jnicusolver.dll
 1218048  Defl:N   176831  86% 2016-07-13 16:42 a7267adb  org/bytedeco/javacpp/windows-x86_64/jnicusparse.dll
   56832  Defl:N    16974  70% 2016-07-13 16:42 123eb80b  org/bytedeco/javacpp/windows-x86_64/jninppc.dll
11445760  Defl:N  1548285  87% 2016-07-13 16:42 52d86459  org/bytedeco/javacpp/windows-x86_64/jninppi.dll
 1021952  Defl:N   133379  87% 2016-07-13 16:42 e2b85717  org/bytedeco/javacpp/windows-x86_64/jninpps.dll
```

**Comment by jfolt** [comment]
I let maven install all files, so I don't even know where to look for such jar file. If am indeed supposed to install something manually let me know.

Thank you for your help. I will wait for 0.4.1 and try it again.

**Comment by saudet** [comment]
Ah, you're running Eclipse. It's known to be problematic with Maven projects. Please try with another IDE (IntelliJ or NetBeans), or on the command line. That should give you something that works.

**Comment by saudet** [comment]
Here's a neat trick:
1. Download http://www.dependencywalker.com/depends22_x64.zip and extract it somewhere
2. Call the following at the beginning of the `main()` method:
```java
try {
    Loader.load(cudnn.class);
} catch (UnsatisfiedLinkError e) {
    new ProcessBuilder("c:/path/to/depends.exe", Loader.getTempDir() + "/jnicudnn.dll").start().waitFor();
}
```
And a nice window telling you what the problem is pops up right away!

**Comment by jfolt** [comment]
This is cool. It does show now that the jnicudnn.dll is being searched in a folder which exists, but it is empty:

c:\Users\jarek\AppData\Local\Temp\javacpp2249647008265374 

I attach screen shot too.

![depends_dialog](https://cloud.githubusercontent.com/assets/13595236/16826281/5a48acfa-4939-11e6-9ca5-7bae4b6fd5d4.png)

**Comment by jfolt** [comment]
Interestingly, there are many other **javacppXXX** folders, and they are not empty (but also apparently not used). For example:

 Directory of c:\Users\jarek\AppData\Local\Temp\javacpp2155265646487094

07/12/2016  06:20 PM    <DIR>          .
07/12/2016  06:20 PM    <DIR>          ..
07/12/2016  06:20 PM           172,544 jnind4j.dll
07/12/2016  06:20 PM           660,128 msvcp120.dll
07/12/2016  06:20 PM           963,232 msvcr120.dll
07/12/2016  06:20 PM        21,825,024 nd4j.dll
               4 File(s)     23,620,928 bytes
               2 Dir(s)  139,692,445,696 bytes free

**Comment by jfolt** [comment]
I searched for jnicudnn.dll in c:\Users\jarek\AppData\Local\Temp\ recursively and it is not there.

**Comment by saudet** [comment]
Old javacpp folders are leftovers from crashed sessions of the JVM... So, it looks like `jnicudnn.dll` isn't getting extracted, and that's probably because `cuda-7.5-1.2-windows-x86_64.jar` isn't getting included in your class path. Looks like a limitation of Eclipse's support for Maven. Try to add it manually like this:
```xml
<dependency>
    <groupId>org.bytedeco.javacpp-presets</groupId>
    <artifactId>cuda</artifactId>
    <version>7.5-1.2</version>
    <classifier>windows-x86_64</classifier>
</dependency>
```
That will eventually get fixed upstream in the JavaCPP Presets because there's similar issues with sbt and Gradle...

**Comment by jfolt** [comment]
YES!!!

Now it seems to work. No errors, and the jnicudnn.dll is there.

Thank you!

**Comment by jfolt** [comment]
It does work great! My convolution training is now almost twice faster!

Thank you for your help again.
