### ISSUE TITLE
Build issue with cpu and current master

### ISSUE THREAD

**Issue by baedaron** [deeplearning4j/deeplearning4j#9574]
#### Issue Description:
Please describe our issue, along with:

Compilation Error

#### Version Information
Please indicate relevant versions, including, if relevant:

Deeplearning4j version:
CURRENT SNAPSHOT

Platform information (OS, etc):
Windows 10 Pro 20H2 (64Bit)
AMD Ryzen 5 5600X 6-Core Processor
GeForce RTX 3070

CUDA version, if used:
v11.0

NVIDIA driver version, if in use:
v496.76 (DCH)

#### Additional Information:
gcc.exe (Rev1, Built by MSYS2 project) 11.2.0
cmake version 3.22.1
Visual Studio 2019 (Community)

Full log or exception stack trace (ideally in a Gist: gist.github.com):
cd /c/Users/Administrator/Downloads/deeplearning4j
export JAVA_HOME=/c/Program\ Files/Java/jdk1.8.0_281
./change-cuda-versions.sh 11.0
cd libnd4j
export LIBND4J_HOME=$(pwd)
./buildnativeoperations.sh -a native -c cpu -e avx2 -h openblas -p msi -j 12 clean true

-------------------------------------------------------------------------------------
.
.
.
[100%] Linking CXX shared library libnd4jcpu.dll
cd /C/Users/Administrator/Downloads/deeplearning4j/libnd4j/blasbuild/cpu/blas && /C/MSys64/mingw64/bin/cmake.exe -E rm -f CMakeFiles/nd4jcpu.dir/objects.a
cd /C/Users/Administrator/Downloads/deeplearning4j/libnd4j/blasbuild/cpu/blas && /C/MSys64/mingw64/bin/ar.exe qc CMakeFiles/nd4jcpu.dir/objects.a @CMakeFiles/nd4jcpu.dir/objects1.rsp
cd /C/Users/Administrator/Downloads/deeplearning4j/libnd4j/blasbuild/cpu/blas && /C/MSys64/mingw64/bin/g++.exe  -DSD_WINDOWS_BUILD=true -Wa,-mbig-obj -mmmx -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mf16c -mprefetchwt1 -DSD_F16C=true -DF_AVX2=true -mno-avx256-split-unaligned-load -mno-avx256-split-unaligned-store -fmax-errors=3  -fopenmp -O3 -fPIC -D_RELEASE=true  -Wl,-rpath,RIGIN/ -shared -o libnd4jcpu.dll -Wl,--out-implib,libnd4jcpu.dll.a -Wl,--major-image-version,0,--minor-image-version,0 -Wl,--whole-archive CMakeFiles/nd4jcpu.dir/objects.a -Wl,--no-whole-archive @CMakeFiles/nd4jcpu.dir/linklibs.rsp
C:/MSys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(activations.cpp.obj):activations.cpp:(.text+0x463): undefined reference to `shape::subArrayIndex(long long, long long const*, long long const*, int const*, int)'
C:/MSys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(activations.cpp.obj):activations.cpp:(.text+0xad7): undefined reference to `shape::subArrayIndex(long long, long long const*, long long const*, int const*, int)'
C:/MSys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(tile.cpp.obj):tile.cpp:(.text+0x763): undefined reference to `shape::subArrayIndex(long long, long long const*, long long const*, int const*, int)'
C:/MSys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(tile.cpp.obj):tile.cpp:(.text+0x9c3): undefined reference to `shape::subArrayIndex(long long, long long const*, long long const*, int const*, int)'
C:/MSys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(tile.cpp.obj):tile.cpp:(.text+0xbd3): undefined reference to `shape::subArrayIndex(long long, long long const*, long long const*, int const*, int)'
C:/MSys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/nd4jcpu.dir/objects.a(tile.cpp.obj):tile.cpp:(.text+0xd63): more undefined references to `shape::subArrayIndex(long long, long long const*, long long const*, int const*, int)' follow
collect2.exe: error: ld returned 1 exit status
.
.
.

**Comment by agibsonccc** [comment]
@baedaron could you please ensure this is working with cuda 11.2? I literally just compiled this fine with your exact environment not too long ago. If something is missing on at least cuda 11.2 (which is the version we're supporting alongside cuda 11.4) I can take a quick look. I suspect I know what the problem might be but would like to make sure it's reproducible for us. Thanks! cc @quickwritereader 

Edit: @baedaron ensure you're on the latest master as well.

**Comment by quickwritereader** [comment]
@baedaron you are having a problem building CPU or Cuda?

**Comment by quickwritereader** [comment]
I confirm the problem on the cpu build

**Comment by baedaron** [comment]
@quickwritereader 

My mistake! sorry.
It's about CPU.

./buildnativeoperations.sh -a native -c cpu -e avx2 -h openblas -p msi -j 12 clean true
-----------------------------------------------------------------------------------------
@agibsonccc

Yes, the latest master!
currently have no time to upgrade to cuda 11.2!
but as I said to quickwritereader, it's not about cuda.
