### ISSUE TITLE
SLF4J and Conv1D error

### ISSUE THREAD

**Issue by vishavdhanjal** [deeplearning4j/deeplearning4j#6243]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
main() : Unsupported keras layer type Conv1D. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.

**Comment by maxpumperla** [comment]
you should upgrade to 1.0.0-beta or beta2. Conv1D is supported in those versions

**Comment by vishavdhanjal** [comment]
NOW GOT THIS ERROR AFTER UPGRADING TO 1.0.0-beta
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: org/nd4j/linalg/api/complex/IComplexDouble
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5499)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5447)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:213)
	at org.deeplearning4j.nn.conf.dropout.Dropout.initializeHelper(Dropout.java:107)
	at org.deeplearning4j.nn.conf.dropout.Dropout.<init>(Dropout.java:100)
	at org.deeplearning4j.nn.conf.dropout.Dropout.<init>(Dropout.java:80)
	at org.deeplearning4j.nn.conf.layers.Layer$Builder.dropOut(Layer.java:257)
	at org.deeplearning4j.nn.modelimport.keras.layers.convolutional.KerasConvolution1D.<init>(KerasConvolution1D.java:105)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasLayerUtils.getKerasLayerFromConfig(KerasLayerUtils.java:230)
	at org.deeplearning4j.nn.modelimport.keras.KerasModel.prepareLayers(KerasModel.java:220)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:102)
	at org.deeplearning4j.nn.modelimport.keras.KerasSequentialModel.<init>(KerasSequentialModel.java:61)
	at org.deeplearning4j.nn.modelimport.keras.utils.KerasModelBuilder.buildSequential(KerasModelBuilder.java:320)
	at org.deeplearning4j.nn.modelimport.keras.KerasModelImport.importKerasSequentialModelAndWeights(KerasModelImport.java:195)
	at Library.main(Library.java:18)
Caused by: java.lang.ClassNotFoundException: org.nd4j.linalg.api.complex.IComplexDouble
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)

**Comment by treo** [comment]
Setup a Logging implementation in your Dependencies, you will get *a lot more information* about what is going on.

Given this stack trace it looks very much like you have mixed versions, you will have to use the same version for all of your DL4J dependencies.

**Comment by vishavdhanjal** [comment]
Kindly Let me know jdk version compatibility, and all gradle dependencies compatible with that version.

**Comment by raver119** [comment]
@vishavdhanjal show your gradle conf, we'll check it out.

**Comment by vishavdhanjal** [comment]
I got it gradle conf successfully. Thanks for help.
